### ISSUE TITLE
Estándares - Configuración

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#10]
En la pantalla donde se configuran los estándares, actualmente se muestra el árbol del lado izquierdo y del lado derecho el detalle de la cláusula.
En esa pantalla de la derecha,  quitar el encabezado, es decir... lo que se señala en amarillo... y en lugar de ello, resaltar del lado izquierdo la cláusula donde estamos parados..

<img width="934" alt="estandar" src="https://user-images.githubusercontent.com/2912775/110829782-1f623a80-825e-11eb-9f03-e6a81a4018c4.PNG">

**Comment by jccastillo0007** [comment]
done
