### ISSUE TITLE
Configurar un Estándar - no permitir borrarlo una vez iniciada su configuración.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#12]
Una vez que un estándar ya tiene capturada parte de la configuración, no debe permitir borrarse.

Esto es, que en la pantalla de estándares lo eliminen del checkbox. Ahí deberá pasar a ser solo lectura.

Para eliminarlo de ahí, tendrían que eliminar tooooda la configuración capturada en la pantalla de "configurar estándar"

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
Ya no permite borrarlo, pero en la configuración no guarda nada.
Es decir, asigno un estándar al cliente activo.
Luego me voy a asociar archivos a las cláusulas.
Le doy guardar e indica que si lo guardó (falta que permita guardar responsables, pero eso es oootra historia).
Cuando salgo y regreso a ese menú, los archivos asociados a las cláusulas que se capturaron previamente ya no los muestra. Y si inhibe el borrado del estándar, pero no tiene asociados los archivos.

**Comment by jccastillo0007** [comment]
quite esta funcionalidad porque tiene un defecto que bloquea mas las pruebas de lo que ayuda

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
Ahorita en producción está muy raro.
Pantalla de estándares:
Tiene únicamente el primero seleccionado (solo lectura)

Pantalla de configuración de estándares:
Aparecen 2, el primero y segundo.

En la pantalla de estándares, seleccioné el segundo, le di guardar, dice que si lo guardó, pero cuando salgo y regreso a la pantalla, no lo tiene seleccionado.

En la pantalla de configuración de estándares, borré todo para ambos estándares, como para poder borrarlos en la pantalla de estándares. Pero no, no me lo permite. No se cual sea el candado.

El punto es... si los estándares en la pantalla de configuración, están vacíos, si debe permitir borrarlos.
Y si ya se tiene un estándar y luego le quieres agregar otro, debe permitir hacerlo.

**Comment by jccastillo0007** [comment]
fixed
