### ISSUE TITLE
Listado de Procesos - falta asignar responsables del proceso

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#14]
Recordar que para asignar el o los responsables del proceso, se deberá opcionalmente capturar el área y puesto, antes de elegir el usuario.

**Comment by jccastillo0007** [comment]
listo, al momento de guardar el proceso.. ya se puede seleccionar los usuarios previamente creados...

aún hay un detalle al momento de guardar los procesos asignados a un estándar

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
si se puede asociar, pero como los organigramas serán enormes, entonces hay que poner los filtros de puesto y área como opcionales al momento de elegir al responsable. Eso está en otro issue.
