### ISSUE TITLE
Asociar el Listado de Procesos a UN estándar

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#15]
En la reunión ayer con el primo, surgió el tema de cuando un mismo cliente cuenta con mas de un estándar definido.
Dice que los procesos para cumplir cada estándar son distintos, entonces, se deben manejar de manera independiente.

Esto quiere decir que cada estándar deberá tener asociado su propio listado de procesos.

**Comment by jccastillo0007** [comment]
ya se muestra la lista de estándares soportados, ahorita se esta cambiando el código para solo mostrar los previamente configurados.

hay que empezar a ver los estilos para que no parezca chile mole y pozole.

**Comment by RigoFlores** [comment]
Pero este issue se refiere a que se debe asociar un listado de procesos, por cada uno de los estándares que se den de alta para un cliente en particular.

Es decir si para el cliente TI Aplicada, eligieron 2 estándares, entonces deberán capturar 2 listados de procesos independientes. Y solo deben aparecer esos 2 estándares asociados al cliente, al momento de capturar el listado de procesos

**Comment by jccastillo0007** [comment]
done

**Comment by RigoFlores** [comment]
no puedo validarlo, ya que no permite agregar un estándar, una vez que guardaste solo un estándar inicialmente.

**Comment by RigoFlores** [comment]
ya le quitaste el candado, pero ahora no permite guardar el proceso cuando se ha capturado el árbol

**Comment by jccastillo0007** [comment]
fixed

**Comment by RigoFlores** [comment]
En pru, al parecer si lo está almacenando
