### ISSUE TITLE
Descripción de Cláusulas - actualizar a última versión del dropbox

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#16]
Ya me aventé la chinga de corregir y revisar cada descripción de cláusula, de los 4 estándares.
Ya la subí al dropbox, hace tiempo.
Y al presentar con el primo, pues sigue mostrándose la anterior que tiene cosas como #02bla bla bla... es algo muy simple, pero se nota que en esa parte no se avanzó, respecto a al presentación anterior.

**Comment by jccastillo0007** [comment]
chiaaa, ya esta

**Comment by RigoFlores** [comment]
Oye, ahora no despliega los caracteres especiales, tipo acentos y ñ's.
Abro otro o aquí le seguimos?

**Comment by jccastillo0007** [comment]
aqui le sigo... eso debe ser configuración de mysql

**Comment by jccastillo0007** [comment]
listo
