### ISSUE TITLE
Listado de Procesos - Falta agregar los formatos generales (archivos) a todo el listado.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#17]
En este caso, los archivos son a nivel general, a diferencia de estándares, que son a nivel de cada cláusula.

**Comment by jccastillo0007** [comment]
ya agregamos el controlador, pero aún no funciona al 100

**Comment by jccastillo0007** [comment]
ya esta funcionando para nuevos archivos, tenemos un problema cuando se actualizan archivos

**Comment by RigoFlores** [comment]
tons not fitset yet...

**Comment by jccastillo0007** [comment]
fixed
