### ISSUE TITLE
Catálogo de Usuarios - no está almacenando varios campos

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#19]
Cuando le das guardar y luego lo consultas, no almacena puesto, privilegio, área, áreas de influencia, jefe superior.

**Comment by RigoFlores** [comment]
De igual manera, lo que sería la edición no funciona. 
Esto es si algún usuario ya almacenado, lo eliges de la lista, y le modificas algún dato, crea ooootro registro, únicamente con el dato o datos que cambiaste, los demás los deja vacíos.
Ejemplo, elijo cualquier usuario y le cambio el número telefónico y le doy guardar, entonces agregará un usuario con todos los campos vacíos, excepto el número telefónico que le asignará el que se cambió.

**Comment by jccastillo0007** [comment]
a chinga, eso crei que ya lo había corregido

**Comment by RigoFlores** [comment]
Si, ya no duplica el registro si lo editas y guardas.
Ahora queda el tema que no almacena todos los datos.

**Comment by jccastillo0007** [comment]
fixed
