### ISSUE TITLE
Configurar estándar - muestra archivos asociados cuando no debería.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#21]
La configuración de un estándar en el proceso es:
1. Dar de alta cliente
2. Dar de alta organigrama
3. Indicar cuál o cuáles estándares aplicarán para el cliente elegido.
4. Configurar estándar.

OK, yo realicé los 3 primeros pasos. Y cuando me fui al paso 4, resulta que ya tiene asociados algunos archivos a las cláusulas, cuando apenas se definió en el paso 3 cuáles estándares aplicarían.

Creo que es tema de consistencia de datos. Mientras no esté implementada la consistencia, las tablas van a estar chuecas.

**Comment by jccastillo0007** [comment]
eso es por todas las pruebas que nosotros hacemos..

crea un usuario master que nosotros no toquemos para que no veas ese tipo de inconsistencia

**Comment by RigoFlores** [comment]
En la liga de producción que me enviaste... alwaysthere.com.mx:5200/home, ahí es donde estoy trabajando.
Ahí capturé varios archivos asociados a las primeras cláusulas del estándar ISO9001, del cliente TI Aplcada.
Los asocié a todas las cláusulas derivadas del 4 Contexto de la organización.
Los guardé y dice que si los guardó.

Me cambio de menú y regreso, a este de configuración y ya no muestra los archivos.
