### ISSUE TITLE
CATÁLOGOS DE LA APLICACIÓN - ORDENAR ALFABÉTICAMENTE Y PRESENTAR POR MATCH

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#22]
En todos los catálogos, que por lo que veo, serán en forma de lista, se hace necesario y casi debería estar ya hecho eso, en el componente de angular material, que se ordenen lexicográficamente (o al menos alfabéticamente), y que conforme vas tecleando en la lista, aparezcan las ocurrencias que hacen match con lo tecleado...

por ejemplo, empiezas a teclear GER (de gerencia), y te debe llevar a ese elemento de la lista.

Así como lo hacemos en FacturaT

**Comment by jccastillo0007** [comment]
fixed... ya se ordenan los resultados... ojo.. el empezar a escribir ya funciona, si eligen un dropdown y teclean , se va a elegir la primer coincidencia

aún no esta en prod, pero lo marco como fixed para ver que nos falta

**Comment by RigoFlores** [comment]
estaría faltando el de clientes, los del organigrama ya quedaron bien

**Comment by jccastillo0007** [comment]
fixed,

**Comment by jccastillo0007** [comment]
ahora si ya esta en prod
