### ISSUE TITLE
Catálogos en todo lo que es el organigrama - no permitir duplicados

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#23]
Acabo de capturar registros duplicados y si lo permite.
No debe hacerlo. Me refiero al campo nombre. La descripción pues ahí no hay tanto problema.

**Comment by RigoFlores** [comment]
Para el catálogo de usuarios, considerar además la nómina, por el caso que se llamen igual 2 usuarios.

**Comment by jccastillo0007** [comment]
ya esta la validación, pero en caso de duplicado, no esta mostrando un mensaje de error en pantalla, ando viendo como mostrarlo.

**Comment by RigoFlores** [comment]
si, ya vi que no permite, pero si hace falta el mensaje para que el usuario sepa lo que está pasando.

**Comment by jccastillo0007** [comment]
ya agregué el mensaje de error, no sé proque la primera vez no me funciono .... esto aún no esta en prod, estoy esperando un merge de Martín para subirlo
