### ISSUE TITLE
Configuración - Estándares, no permite agregar un estándar después que se había guardado uno anteriormente.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#24]
Trataré que todas mis pruebas sean con el cliente TI Aplicada, a menos que se indique lo contrario. Ambiente de producción.

Primero elegí un estándar ISO 9001, y le di guardar. Si lo guardó.
Me fui a configurar las primeras cláusulas agregando archivos en las primeras clausulas y le di guardar y el mensaje es que si lo guardó.
Si me salgo y regreso a esa opción ya no muestra los archivos, aunque ese estándar ya no permite borrarlo desde configuración-estándar. Está bien, siempre que muestre los archivos asociados a las cláusulas.

Bueno, pero este issue se trata que si me voy a configuración - estándares, y ya almacenado el primero, ahora trato de agregar un estándar, es decir elegir uno segundo estándar, y le doy guardar dice que si lo guarda, pero si salgo y regreso a esta opción, no aparece seleccionado.

Tal pareciera que una vez que seleccionaste un estándar y lo almacenas y lo empiezas a configurar. A partir de ahí, ya no te permite agregar otro estándar para ese mismo cliente.

**Comment by jccastillo0007** [comment]
fixed

Tenemos el defecto de que no se permita eliminar un estándar cuando ya se esta configurando, se quito por el momento esa validación

**Comment by RigoFlores** [comment]
Si, aunque de hecho van de la mano.
Para yo poder validar este issue, primero debería permitir almacenar solo uno.
Luego, permitir agregar uno mas. Pero si elijo solo uno, y le doy guardar, y luego salgo y regreso a esa pantalla, aparece así:

<img width="239" alt="estándar" src="https://user-images.githubusercontent.com/2912775/116131607-36d07800-a692-11eb-8c45-8956c633ec57.PNG">

Es decir, ahí no está señalando que ya se almacenó uno. Aparece como si no tuviera ninguno asociado ese cliente.
Sin embargo, en configuración de estándar, si despliega solo uno y "al guardar uno mas", esto es volver a seleccionar 2, entonces en configuración del estándar, si aparecen los 2.

En resumen, está medio corregido este issue, jejeje.

**Comment by jccastillo0007** [comment]
es lo que mencioné arriba, el defecto que tenemos es al mostrar cual estándar ya se había seleccionado.. se arreglará al mismo tiempo.

asi que este issue debería cerrarse, y el fix del otro problema se arreglará en el issue #12

**Comment by RigoFlores** [comment]
SIGUE IGUAL, AL MENOS VISUALMENTE NO ALMACENA UNO NUEVO, YA QUE TENÍA UNO PREVIO

**Comment by jccastillo0007** [comment]
ya platicamos este defecto, que ya esta corregido

**Comment by jccastillo0007** [comment]
fixed * 2

**Comment by RigoFlores** [comment]
OK, para documentar.
En la pantalla de estándares, quedó como solo lectura un estándar que ya haya iniciado su configuración o tenga iniciada su captura de listado de procesos. Aún cuando borres todo del estándar o del listado de procesos, se mostrará en solo lectura.

Por otro lado, se mostrará el check box en formato lectura y escritura, cuando en ese estándar aún no se ha iniciado su configuración, ni tiene listado de procesos asociado.

ya solo faltaría el botón mágico de "borrar estándar", el cual elimina toda configuración de estandar así como todo listado de procesos asociado al mismo.
