### ISSUE TITLE
Pantalla de estándares - indicar si un estándar fue agregado para ser configurado

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#26]
Como platicamos ayer, quedaría así la pantalla de estándares:

A) Sin check (palomita), un estándar que nunca ha sido agregado para ese cliente.
B) Con check habilitado, para un estándar que se agregó, pero que no hay iniciado su configuración. Solo se seleccionó y se guardó en esa pantalla, la de estándares.
C) Con check deshabilitado, para un estándar que se agregó y ya inició su configuración. Esto es en la pantalla de Configuración de Estándar se han agregado archivos y/o definido responsables de estándar. O también se ha iniciado al configuración de los procesos. Listado de procesos.

**Comment by jccastillo0007** [comment]
done
