### ISSUE TITLE
Equus - Implementar el acceso seguro y controlado a la aplicación

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#27]
En principio habrá un superadministrador, y el resto serán usuarios que tendrán privilegios, de acuerdo a su configuración.
Aunque de igual manera podrían existir varios usuarios con perfil de superadmin. Eso como lo controlaremos o cómo se definirán?

Entonces debemos implementar que la primera vez que acceda un usuario a la plataforma, su usuario sea el primer correo capturado (en caso que eventualmente tenga mas de un correo).
Después de reconocer como un usuario del sistema, deberá asociarlo al cliente (empresa) que pertenece.
La primer vez que se firme, le pediré que capture su contraseña, con los estándares ya mas o menos definidos para las contraseñas.
Una vez capturada, validarla de alguna manera para que se le permita acceso al sistema.

**Comment by jccastillo0007** [comment]
done
