### ISSUE TITLE
Cliente Activo o actual

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#3]
Siempre tener visible y claro cuál es el cliente activo o actual.

Cuando se está configurando el sistema, se debe indicar cuál es el cliente activo.
Cuando algún usuario del sistema acceda, igualmente se deberá mostrar el cliente, en este caso pues será el cliente al que pertenece el usuario que ingresó.

**Comment by jccastillo0007** [comment]
Para la pantalla de organigrama, ya se muestra el cliente seleccionado

**Comment by RigoFlores** [comment]
Bueno, se muestra si, pero no cambia los catálogos.
Es decir, capturé un cliente nuevo, me voy a la opción de configurar y muestra los mismos datos en las tablas de organigrama, que se tenían antes de dar de alta el cliente.
En este caso deberían estar totalmente vacíos, ya que el cliente es nuevo

**Comment by RigoFlores** [comment]
Una vez seleccionado el cliente, todo lo que haga el sistema se refiere a ese mismo cliente. Entonces el cliente, y en particular el ALIAS debería ser la llave primaria de tooooodo lo demás del sistema.
Es decir, el Alias no debe repetirser ya que identificará de manera única a cada cliente dentro del sistema

**Comment by jccastillo0007** [comment]
ok, entendido... pero ojo, el alias no es la llave principal, ese dato es un key que se asigna al cliente, sin importar el resto de datos

**Comment by RigoFlores** [comment]
OK, pero entonces se debe validar que el alias no se repita. Tampoco el nombre. 
Aunque la llave primaria principal, tenemos que validar que no se repitan algunos datos del cliente, creo yo:
RFC
Nombre
Alias

Es decir, no pueden capturar un RFC o nombre o Alias que ya exista.

**Comment by jccastillo0007** [comment]
ya se crean catálogos asignados al cliente seleccionado... ya se esta validando el rfc, nombre y alias, peero aún no esta listo para pruebas

**Comment by jccastillo0007** [comment]
ya se encuentran en todas las pantallas que están en desarrollo.
falta el team de inhibir los menús y opciones si no se tiene un cliente seleccionado, pero ese es otro ticket

**Comment by jccastillo0007** [comment]
psss ya hay que probar k... si no como sabemos si vamos bien o nos regresamos

**Comment by RigoFlores** [comment]
acabo de capturar clientes en el ambiente de pro.
