### ISSUE TITLE
Equus -Generar Organigrama

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#30]
A partir de los catálogos capturados en Organigrama, generar el organigrama en modo gráfico:

Cómo estaremos identificando a la cabeza de la organización? Propuesta que sea la única persona donde su jefe es el mismo.
O la otra propuesta es que la descripción de su puesto, sea "RESPONSABLE PRINCIPAL".

A partir de identificar la raiz del organigrama, formarlo de acuerdo al área - puesto - jefe superior del personal. Pr ejemplo:

Gerente General - Próculo Adame
----- Gerente Administración- Virginia Loera
         ----- Auxiliar Contable - Alma María Rico

Toda área representa un nuevo nodo en el organigrama.
Debajo de cada nodo, se indicarán los puestos que se encuentran en dicha área.
A cada puesto le corresponderá un nombre.
Dependiendo del jefe superior, se irán uniendo las ramas.

Al final el organigrama podrá ser exportado a PDF.

**Comment by RigoFlores** [comment]
Estoy leyendo la spec, y ahí se indica que debería capturarse también el puesto inferior.
Crees que sea necesario para generar el organigrama??

**Comment by jccastillo0007** [comment]
duplicado con el issue 9, chiaaa
