### ISSUE TITLE
Cuando eres responsable de procesos, y accedes con tu usuario deben aparecer esas actividades

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#35]
En el mapa de procesos, se asignan responsables. Por ejemplo, estos 4 procesos están asignados a 2 responsables.

<img width="482" alt="procesos" src="https://user-images.githubusercontent.com/2912775/184681151-4a44d280-de57-4b11-89cc-50e549dd96b4.PNG">

Si entras con cualquiera de esos usuarios a Equus, deben aparecer las actividades de las cuales es responsable.
Particularmente en procesos, debe aparecer el nombre del proceso del cual son responsables.

En este ejemplo que menciono, para uno de los usuarios no aparece ninguna actividad.
Para el otro, aparece un proceso que dice que es "proceso 1", en lugar del nombre correcto.

total, no aparecen todas las actividades y por otro lado, no aparecen los nombres del proceso.

**Comment by jccastillo0007** [comment]
fixed...

ya esta aplicado en PRO, y verifiqué que se asignaran correctamente los procesos

**Comment by RigoFlores** [comment]
ok.
