### ISSUE TITLE
En el menú de procesos, no está almacenando los archivos que se suben.

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#36]
Cuando accedes al menú de configuración - mapa de procesos, ahí tu defines tus procesos y los archivos que serán comunes para todos ellos. Si los sube y le das guardar, y dice que si los guardó.
Pero si te cambias de menú y regresas, no aparecen los archivos que cargaste previamente.

**Comment by RigoFlores** [comment]
O mas bien no los muestra, ya que si entro con el usuario dueño del proceso, si le aparece el archivo que subí.
Pero en la pantalla de configuración no los muestra y aparenta que no lo guardó.

**Comment by RigoFlores** [comment]
Entonces en configuración de procesos estás a ciegas, ya que no muestra los archivos que ya has subido.
Posiblemten podrías repetirlos y lo permitiría.

**Comment by RigoFlores** [comment]
De hecho pasa lo mismo con el menú de estándares. 
Subí en la cláusula 4.3 del ISO9001, y no la está mostrando en la configuración de estandar.
SI entro con el usuario jjimenez@careags.com, no le aparecen los archivos del estándar 4.2, y si aparece el del 4.1

Total, está muy raro, errático el comportamiento

**Comment by jccastillo0007** [comment]
Repetido con el issue 40
