### ISSUE TITLE
Catálogo de Usuarios - permitir varios privilegios, áreas de influencia

### ISSUE THREAD

**Issue by RigoFlores** [jccastillo0007/equus-ui#5]
Un mismo usuario, podrá tener definidos varios privilegios y áreas de influencia.

**Comment by RigoFlores** [comment]
Yo creo que aquí, mas que lista, debe ser un listado donde puedan darle check a una o varias opciones.
De esa manera quedaría mucho mas simple.
Al dar click en privilegios o áreas de influencia, que se abriera una ventana con la lista y check boxes para elegir uno o varios.

**Comment by jccastillo0007** [comment]
fixed
